name: Inhaltlicher Kommentar 1
description: Kommentar bezieht sich auf inhaltliche Festlegungen.
title: "Inhaltlich: ..."
body:
  - type: markdown
    attributes:
      value: |
        Bitte vergib zunächst Labels, damit wir den Kommentar besser einschätzen können die Auswahl findest du unten
  - type: input
    id: contact
    attributes:
      label: Kontakt
      description: Wie können wir dich kontaktieren, wenn wir weitere Infos brauchen?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Fehlerbeschreibung
      description: Was ist das konkrete Problem?
      placeholder: Die Anforderung geht über das Ziel hinaus
      value: "Anforderung zu stringent!"
    validations:
      required: true
  - type: textarea
    id: change-suggestion
    attributes:
      label: Änderungsvorschlag
      description: Was soll geändert werden?
      placeholder: Was sollte deiner Mainung nach verbessert werden?
      value: "bitte ..."
    validations:
      required: true   
  - type: textarea
    id: organisation
    attributes:
      label: Organisation
      description: Bezeichnung deiner Organisation
      placeholder: Bundesamt für Kartografie und Geodäsie
      value: "BKG"
    validations:
      required: false
