name: Inhaltlicher Kommentar 1
description: Kommentar bezieht sich auf inhaltliche Festlegungen.
title: "Inhaltlich: ..."
  - type: markdown
    attributes:
      value: |
        Bitte vergib zunächst Labels, damit wir den Kommentar besser einschätzen können die Auswahl findest du unten
